# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  spoti-picker:
    networks:
      - caddy
    build: .
    ports:
      - "3000:3000"

networks:
  caddy:
    external: true
